#!/bin/bash
IMAGE=/tmp/screen.png
TEXT=/tmp/locktext.png
GRIM=${HOME}/.local/bin/grim


${GRIM} /tmp/screen.png

convert /tmp/screen.png -scale 25% -blur 0x2 -scale 400% -fill black -colorize 50% /tmp/screen.png
[[ -f $1 ]] && convert /tmp/screen.png $1 -gravity center -composite -matte /tmp/screen.png

[ -f $TEXT ] || {
    convert -size 1920x60 xc:black -font Liberation-Sans -pointsize 26 -fill white -gravity center -annotate +0+0 'Type password to unlock' $TEXT;
}

#convert $IMAGE -gravity center -geometry +0+200 -composite $IMAGE
convert -crop 2X1@ +repage ${IMAGE} /tmp/screen.png
swaylock -s fit -i eDP-1:/tmp/screen-0.png -i DP-1:/tmp/screen-1.png --font hack


