#!/bin/bash

GRIM=$(which grim)
FILENAME=$(date +'%Y-%m-%d-%H%M%S_grim.png')
FILEPATH=$(xdg-user-dir PICTURES)/screenshots

mkdir -p ${FILEPATH}

${GRIM} $(xdg-user-dir PICTURES)/screenshots/$FILENAME

notify-send "Created Screenshot" ${FILENAME} -t 50000
