language: haskell

sudo: required

git:
  submodules: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

ghc:
  - 7.10.3

install:
  - cabal install shellcheck
script:
  - ./test.sh

notifications:
    email: true

#after_success: |
#  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
#  tar xzf master.tar.gz &&
#  cd kcov-master &&
#  mkdir build &&
#  cd build &&
#  cmake .. &&
#  make &&
#  sudo make install &&
#  cd ../.. &&
#  rm -rf kcov-master &&

after_success: |
  mkdir -p coverage &&
  kcov coverage test.sh &&
  bash <(curl -s https://codecov.io/bash)
