# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """${custom.distrobox}\
$hostname\
$username\
$battery\
$python\
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""
right_format = "$time"

# format = """

# $battery\
# $username\
# $docker_context\
# $directory\
# $git_branch\
# $git_status\
# $git_state\
# $git_metrics\
# $python\
# $character
# """


command_timeout = 10000

[hostname]
ssh_only = true
ssh_symbol= '🌐'
format   = '[$ssh_symbol](bold blue)[$hostname](bold red) '
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[username]
style_root = 'bold red'
style_user = 'bold yellow'
format = '[$user]($style) '
show_always = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](bold purple)"
error_symbol   = "[❯](bold red)"


[container]
symbol = "🫙"
format = '[$symbol \[$name\]]($style) '


# [git_status]
# style = "bold yellow"
# format = "[$all_status$ahead_behind]($style) "
# conflicted = "="
# ahead = " up:${count}"
# behind = " down:${count}"
# diverged = " up:${ahead_count} down:${behind_count}"
# untracked = " ?${count}"
# stashed = ""
# modified = " !${count}"
# staged = " +${count}"
# renamed = " r${count}"
# deleted = " x${count}"


[git_branch]
symbol = ""
style = "bold purple"
format = "[$branch]($style) "

[git_status]
format     = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)]($style)"
style = "bold yellow"
# conflicted = "🏳"
# ahead      = "💨"
# behind     = "😰"
# diverged   = "😵"
# untracked  = "🤷‍"
# stashed    = "📦"
# modified   = "📦"
# staged     = "➕"
# renamed    = "👅"
# deleted    = "🔥"
modified = " !${count}"
staged = " +${count}"
renamed = " r${count}"
deleted = " x${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style  = "bright-purple"

[cmd_duration]
format = "[$duration]($style)"
style  = "yellow"

[python]
format = "[$virtualenv]($style) "
style  = "bright-green"

[os]
disabled = false

[os.symbols]
Alpaquita        = "🔔"
Alpine           = "🏔️ "
Amazon           = "🙂"
Android          = "🤖"
Arch             = "🎗️ "
Artix            = "🎗️ "
CentOS           = "💠"
Debian           = "🌀 "
DragonFly        = "🐉"
Emscripten       = "🔗"
EndeavourOS      = "🚀"
Fedora           = "🎩 "
Bluefin          = "🦖 "
FreeBSD          = "😈"
Garuda           = "🦅 "
Gentoo           = "🗜️ "
HardenedBSD      = "🛡️ "
Illumos          = "🐦 "
Linux            = "🐧"
Mabox            = "📦"
Macos            = "🍎"
Manjaro          = "🥭"
Mariner          = "🌊"
MidnightBSD      = "🌘"
Mint             = "🌿"
NetBSD           = "🚩"
NixOS            = "❄️ "
OpenBSD          = "🐡"
OpenCloudOS      = "☁️ "
openEuler        = "🦉"
openSUSE         = "🦎"
OracleLinux      = "🦴"
Pop              = "🍭"
Raspbian         = "🍓"
Redhat           = "🎩 "
RedHatEnterprise = "🎩 "
Redox            = "🧪"
Solus            = "⛵"
SUSE             = "🦎 "
Ubuntu           = "🎯 "
Unknown          = "❓ "
Windows          = "🪟 "

[battery]
full_symbol        = '🔋 '
charging_symbol    = '⚡️ '
discharging_symbol = '💀 '
disabled           = false

[line_break]
disabled = true

[custom.ssh_no_keys]
description = "SSH missing keys"
when        = "ssh-add -l | grep -q 'no identities'"
command     = "echo 🚫"
format      = "$symbol[$output]($style) "
shell       = ["bash", "--noprofile", "--norc"]
symbol      = "🔑"
style       = "bold fg:red"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
style = "dimmed white"

# [custom.ssh_keys]
# description = "SSH key count"
# when        = "ssh-add -l | grep -v -q 'no identities'"
# command     = "ssh-add -l | grep -v 'no identities' | wc -l"
# format      = "$symbol[$output]($style) "
# shell       = ["bash", "--noprofile", "--norc"]
# symbol      = "🔑"
# style       = "bold fg:green"

# [custom.toolbox]
# description = "The activated toolbox container"
# command     = "echo $(. /var/run/.containerenv; echo ${name}: ${DISTTAG%container})"
# when        = """ [[ -f /run/.containerenv && -f /run/.toolboxenv ]] """
# style       = "bold red"
# format      = "[$symbol \\[$output\\]]($style) "
# disabled    = false
# symbol      = "📦"

[custom.distrobox]
description = "Displays name of the activated distrobox container"
# box symbol from NerdFonts
symbol = "🫙"
# activates when the command in "when" returns 0 (succeed / true)
# we check for the $CONTAINER_ID variable as described in https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#detect-if-youre-in-a-distrobox
when = "[[ ! -z \"${CONTAINER_ID}\" ]]"
# the output of this command will be provided in $output for the format
# here we get the name of the distrobox
command = "echo ${CONTAINER_ID}"
# format in the shell
format = "[ $symbol $output ]($style)"
disabled = false
# apply your favorite style here...
style = "bold green"