#!/bin/bash

SCROT=/usr/bin/scrot
FILENAME="${HOSTNAME}_$(date +'%Y-%m-%d-%H%M%S.png')"
THUMBNAME="${HOSTNAME}_$(date +'%Y-%m-%d-%H%M%S-thumb.png')"
FILEPATH="${HOME}/Pictures/screenshots"

mkdir -p "${FILEPATH}"

echo "${FILEPATH}/${FILENAME}"

${SCROT} --select --thumb "${FILEPATH}/${FILENAME}"

notify-send "Created Screenshot" "${FILENAME}" -t 50000 -i "${FILEPATH}/${THUMBNAME}"



