_default:
    just --list
# ssh into my work laptop
worktop:
    ssh worktop

# Work: Start working on VMware Ansible stuff
work_vmware:
    /usr/bin/code /mnt/worktop/home/Documents/src/Ansible/vmware
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/Ansible/vmware && distrobox enter ansible'

work_linux:
    /usr/bin/code /mnt/worktop/home/Documents/src/Ansible/linux_template
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/Ansible/linux_template && distrobox enter ansible'

work_docker:
    /usr/bin/code /mnt/worktop/home/Documents/src/Ansible/docker-deploy
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/Ansible/docker-deploy && distrobox enter ansible'
# Work: Work on interplex
work_interplex:
    /usr/bin/code /mnt/worktop/home/Documents/src/web/interplex.methnet.org
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/web/interplex.methnet.org && distrobox enter interplex'

work_mkdocs:
    /usr/bin/code /mnt/worktop/home/Documents/src/mkdocs-builder
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/mkdocs-builder && distrobox enter fedora'

work_odba:
    /usr/bin/code /mnt/worktop/home/Documents/src/odba-docs/
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/odba-docs/ && distrobox enter fedora'

work_nagios:
    /mnt/worktop/home/Documents/src/python/nagios-gen
    ssh -t jharry@worktop.mcharryville.space 'cd Documents/src/python/nagios-gen/ && distrobox enter fedora'

# Just start mining on worktop
work_mine:
    ssh -t jharry@worktop.mcharryville.space 'cd ~/moneroocean/ && sudo ~/moneroocean/miner.sh'


# Start working on the RK1 cluster
ansible_rk1:
    /usr/bin/code ~/Documents/src/Ansible/ansible-rk1-cluster/
    cd ~/Documents/src/Ansible/ansible-rk1-cluster/ && distrobox enter ansible

ansible_docker:
    /usr/bin/code ~/Documents/src/Ansible/ansible-network
    cd ~/Documents/src/Ansible/ansible-network && distrobox enter ansible


# Some random scripts converted into just

# Display Public IP Address
public_ip:
    @curl -s https://ifconfig.me/ip -4
    @echo ""
    @curl -s https://ip.wtf

# Flush DNS Cache (Linux)
flush_dns:
    resolvectl flush-caches
    sudo systemd-resolve --flush-caches
    echo "Flushed DNS cache."

# Generate a new ed25519 SSH Key
make_key:
    ssh-keygen -t ed25519 -C "Generated KEY $(date +%Y-%m-%d)"

# Clean up cache files {WIP}
clean_caches:
    @echo "Cleaning up cache files..."
    @sudo dnf autoremove -y
    @sudo dnf clean all

    # CACHE_PATH="${HOME}/.cache"
    # rm -rf "${CACHE_PATH}/.thumbs/*"
    # rm -rf "${CACHE_PATH}/flatpak/*"

    # #Clean up browsers
    # rm -rf "${CACHE_PATH}/vivaldi/*"
    # rm -rf "${CACHE_PATH}/google-chrome/*"
    # rm -rf "${CACHE_PATH}/google-chrome-beta/*"
    # rm -rf "${CACHE_PATH}/mozilla/*"
    # rm -rf "${CACHE_PATH}/chromium/*"

    # #Clean Up apps
    # rm -rf "${CACHE_PATH}/libgweather/*"
    # rm -rf "${CACHE_PATH}/gnome-software/*"
    # rm -rf "${CACHE_PATH}/evolution/mail/*"


# Check emoji
check_emoji:
    @echo "If you see emojis below, color emoji work in your terminal!"
    @echo "If you see boxes or blank spaces, color emoji do NOT work in your terminal!"
    @echo ""

    @echo "♥👍😍🙊🥱🥺✨✅🎊🏄"
# Setup Papirus Icon Theme 
setup_papirus_icons:
   wget -qO- https://git.io/papirus-icon-theme-install | env DESTDIR="$HOME/.local/share/icons/" sh

# Start Monero Ocean Miner
mine:
    @sudo ~/moneroocean/tmux_miner.sh

rebuild_distrobox:
    distrobox assemble create --file ${HOME}/.config/distrobox/distrobox.ini