[fedora]
image=fedora:latest
additional_packages=tmux git cargo btop micro pass rsync cmake systemd nano
additional_packages=pip python3 python-devel libffi-devel chromium chromedriver
additional_packages=gcc gcc-c++ # Packages to build stuff
init=false
nvidia=false
pull=true
root=false
replace=true 
start_now=true

[ansible]
image=fedora:41
additional_packages=tmux git cargo btop micro pass rsync systemd nano
additional_packages=ansible python-pip python-dnf python-pip python ansible ansible-lint python3-pyvmomi python3-passlib
init=true
nvidia=false
pull=true
root=false
replace=true
start_now=true
#init_hooks="pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git"

[debian]
image=debian:latest
additional_packages=tmux git micro pass rsync systemd nano cargo
init=true
nvidia=false
pull=true
root=false
replace=true
start_now=true
#init_hooks=echo 'Acquire::http::Proxy "http://apt-cacher.methnet.org:3142"' >  /etc/apt/apt.conf.d/00aptproxy 

[interplex]
image=debian:12
additional_packages=tmux git micro pass rsync systemd nano cargo
init=true
nvidia=false
pull=true
root=false
replace=true
start_now=true

[php]
image=debian:12
additional_packages=tmux curl unzip wget git
additional_packages=apache2 apache2-utils openssl 
additional_packages=php php-cli php-sqlite3 php-common php-curl php-intl php-ldap php-mbstring php-mysql php-mysqli php-pdo php-pdo-mysql php-xml php-zip php-gd php-sybase php-pgsql php-gd libapache2-mod-php default-mysql-client 
init=false
nvidia=false
pull=true
root=false
replace=true
start_now=true

[php_dev]
image=debian:13
additional_packages=tmux curl unzip wget git
additional_packages=apache2 apache2-utils openssl 
additional_packages=php php-cli php-sqlite3 php-common php-curl php-intl php-ldap php-mbstring php-mysql php-mysqli php-pdo php-pdo-mysql php-xml php-zip php-gd php-sybase php-pgsql php-gd libapache2-mod-php default-mysql-client 
init=false
nvidia=false
pull=true
root=false
replace=true
start_now=true

#init_hooks=echo 'Acquire::http::Proxy "http://apt-cacher.methnet.org:3142"' >  /etc/apt/apt.conf.d/00aptproxy 
